import type { GalleryImage } from "@/lib/types";

/**
 * Lab Photos gallery — the FULL Sarin Lab photo carousel
 * (sarinlab.stanford.edu/lab-photos), migrated 2026-06-30 in the original
 * carousel order. People-focused photos only (no scientific figures, OCT,
 * histology, or publication graphics). One screenshot was excluded; no exact
 * duplicates remained after de-duping the CDN list. Originals preserved in
 * public/images/lab-photos/originals/; display copies (JPEG, long side ≤1600px,
 * natural aspect) in public/images/lab-photos/. Inventory + selection rationale:
 * LAB_PHOTO_INVENTORY.md.
 *
 * Captions are proposed from filenames/visual context (the live site had none);
 * uncertain captions and any identity/date/location claims are flagged in
 * CONTENT_REVIEW_NEEDED.md. Do not name people/dates/events unless supported.
 */
export const GALLERY: GalleryImage[] = [
  // --- Added photos (supplied by the lab, 2026-06-30) ---
  {
    src: "/images/lab-photos/lp-new-01.jpg",
    width: 1200,
    height: 1600,
    alt: "Sarin Lab bowling outing.",
    caption: "Sarin Lab bowling outing.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-new-02.jpg",
    width: 1600,
    height: 1200,
    alt: "Members of the Sarin Lab.",
    caption: "Members of the Sarin Lab.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-new-03.jpg",
    width: 1200,
    height: 1600,
    alt: "Presenting a poster at a research meeting.",
    caption: "Presenting a poster at a research meeting.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-new-04.jpg",
    width: 1600,
    height: 1200,
    alt: "A Sarin Lab dinner.",
    caption: "A Sarin Lab dinner.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-new-05.jpg",
    width: 1600,
    height: 1205,
    alt: "A Sarin Lab outing.",
    caption: "A Sarin Lab outing.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-new-06.jpg",
    width: 1200,
    height: 1600,
    alt: "Presenting a poster at the Society for Investigative Dermatology meeting.",
    caption: "Presenting a poster at the Society for Investigative Dermatology meeting.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-new-07.jpg",
    width: 1600,
    height: 1200,
    alt: "Presenting from the main stage at a conference.",
    caption: "Presenting from the main stage at a conference.",
    category: "Conferences & Talks",
  },
  // --- Carousel photos (original order) ---
  {
    src: "/images/lab-photos/lp-01.jpg",
    width: 1600,
    height: 1200,
    alt: "Sharing research at a scientific poster session.",
    caption: "Sharing research at a scientific poster session.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-02.jpg",
    width: 1200,
    height: 1600,
    alt: "At a scientific poster session.",
    caption: "At a scientific poster session.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-03.jpg",
    width: 1200,
    height: 1600,
    alt: "Sarin Lab members at an event.",
    caption: "Sarin Lab members at an event.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-04.jpg",
    width: 1200,
    height: 1600,
    alt: "Presenting at a research conference.",
    caption: "Presenting at a research conference.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-05.jpg",
    width: 1600,
    height: 1200,
    alt: "Delivering a podium talk at a scientific meeting.",
    caption: "Delivering a podium talk at a scientific meeting.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-06.jpg",
    width: 1200,
    height: 1600,
    alt: "Members of the Sarin Lab.",
    caption: "Members of the Sarin Lab.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-07.jpg",
    width: 1200,
    height: 1600,
    alt: "At a research poster session.",
    caption: "At a research poster session.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-10.jpg",
    width: 1200,
    height: 1600,
    alt: "The Sarin Lab's space at Stanford.",
    caption: "The Sarin Lab's space at Stanford.",
    category: "Lab & Campus",
  },
  {
    src: "/images/lab-photos/lp-11.jpg",
    width: 1600,
    height: 1200,
    alt: "Lab members celebrating Halloween.",
    caption: "Lab members celebrating Halloween.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-12.jpg",
    width: 640,
    height: 480,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-13.jpg",
    width: 1200,
    height: 1600,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-14.jpg",
    width: 481,
    height: 640,
    alt: "A Sarin Lab gathering.",
    caption: "A Sarin Lab gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-15.jpg",
    width: 640,
    height: 480,
    alt: "A Sarin Lab gathering.",
    caption: "A Sarin Lab gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-16.jpg",
    width: 640,
    height: 480,
    alt: "A Sarin Lab gathering.",
    caption: "A Sarin Lab gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-17.jpg",
    width: 1600,
    height: 1200,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-19.jpg",
    width: 960,
    height: 1280,
    alt: "At a research poster session.",
    caption: "At a research poster session.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-20.jpg",
    width: 1600,
    height: 1066,
    alt: "A Sarin Lab team gathering.",
    caption: "A Sarin Lab team gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-22.jpg",
    width: 960,
    height: 640,
    alt: "The Sarin Lab, 2023.",
    caption: "The Sarin Lab, 2023.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-23.jpg",
    width: 1000,
    height: 750,
    alt: "A Sarin Lab lunch.",
    caption: "A Sarin Lab lunch.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-24.jpg",
    width: 1280,
    height: 960,
    alt: "A Sarin Lab lunch.",
    caption: "A Sarin Lab lunch.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-25.jpg",
    width: 1024,
    height: 768,
    alt: "Sarin Lab drinks.",
    caption: "Sarin Lab drinks.",
    category: "Celebrations & Milestones",
  },
  {
    src: "/images/lab-photos/lp-26.jpg",
    width: 1280,
    height: 960,
    alt: "A Sarin Lab gathering.",
    caption: "A Sarin Lab gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-27.jpg",
    width: 932,
    height: 530,
    alt: "A Sarin Lab gathering.",
    caption: "A Sarin Lab gathering.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-28.jpg",
    width: 1600,
    height: 792,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-29.jpg",
    width: 1280,
    height: 960,
    alt: "A lab member presents from the podium.",
    caption: "A lab member presents from the podium.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-30.jpg",
    width: 1280,
    height: 952,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-31.jpg",
    width: 1280,
    height: 960,
    alt: "Sarin Lab members.",
    caption: "Sarin Lab members.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-32.jpg",
    width: 1280,
    height: 960,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-33.jpg",
    width: 1600,
    height: 1200,
    alt: "Sarin Lab members at an event.",
    caption: "Sarin Lab members at an event.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-34.jpg",
    width: 1280,
    height: 960,
    alt: "Sarin Lab members.",
    caption: "Sarin Lab members.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-35.jpg",
    width: 800,
    height: 600,
    alt: "The Sarin Lab at the Society for Investigative Dermatology meeting, 2024.",
    caption: "The Sarin Lab at the Society for Investigative Dermatology meeting, 2024.",
    category: "Conferences & Talks",
  },
  {
    src: "/images/lab-photos/lp-36.jpg",
    width: 1280,
    height: 851,
    alt: "The Sarin Lab team.",
    caption: "The Sarin Lab team.",
    category: "Team & Community",
  },
  {
    src: "/images/lab-photos/lp-37.jpg",
    width: 1600,
    height: 800,
    alt: "Stanford, where the lab is based.",
    caption: "Stanford, where the lab is based.",
    category: "Lab & Campus",
  },
];

/** Filter categories, in display order (the gallery UI prepends "All"). */
export const GALLERY_CATEGORIES: string[] = [
  "Team & Community",
  "Conferences & Talks",
  "Celebrations & Milestones",
  "Lab & Campus",
];
