// AUTO-GENERATED from PubMed E-utilities (term: "Kavita Y Sarin[Author]").
// VERIFIED BIBLIOGRAPHIC DATA ONLY (title/authors/journal/year/PMID/DOI come
// straight from PubMed — nothing invented). Research-area assignment is a
// keyword heuristic and needs human review (see CONTENT_REVIEW_NEEDED.md).
// TODO: VERIFY research-area tags and the total count vs the lab's own list.
// Regenerate with scratchpad/gen-pubs.js. Do not hand-edit individual records.
import type { Publication } from "@/lib/types";

/** All publications shown on the Publications page (most recent first). */
export const ALL_PUBLICATIONS: Publication[] = [
  {
    pmid: "41621664",
    title: "Limited insurance coverage for wigs: A cross-sectional analysis of wig providers in the Bay Area",
    authors: "Caravan S, Akras D, Shareef H, Abdusamad R, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2026,
    date: "June 2026",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41621664/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2026.01.056",
  },
  {
    pmid: "41290043",
    title: "Stigmatization related to cutaneous neurofibromas in neurofibromatosis 1: development, validation and severity strata of the cNF-PUSH-D",
    authors: "Fertitta L, Sarin KY, Romo CG, Bergqvist C, et al.",
    journal: "The British journal of dermatology",
    year: 2026,
    date: "March 2026",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41290043/",
    doiUrl: "https://doi.org/10.1093/bjd/ljaf479",
    image: "/images/recent-work/cnf-push-d.jpg",
    imageAlt: "Correlation matrix of clinical features in neurofibromatosis type 1.",
    featured: true,
  },
  {
    pmid: "40505736",
    title: "Ethical challenges of nonmedical switching and biosimilar substitution",
    authors: "Leeolou MC, Jia JL, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2026,
    date: "March 2026",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40505736/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2025.06.024",
  },
  {
    pmid: "41460725",
    title: "Dissection of Gαs and Hedgehog Signaling Cross-talk Reveals Therapeutic Opportunities to Target Hedgehog-Dependent Tumors",
    authors: "Krantz S, Bell BA, Lund K, Salinas Parra N, et al.",
    journal: "Cancer research",
    year: 2026,
    date: "February 2026",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41460725/",
    doiUrl: "https://doi.org/10.1158/0008-5472.CAN-25-1109",
    image: "/images/recent-work/hedgehog.jpg",
    imageAlt: "Schematic showing how Hedgehog pathway signaling drives tumor growth and response to an SMO inhibitor.",
    featured: true,
  },
  {
    pmid: "41399671",
    title: "Phenotypic characterization of neurofibromatosis type 1 in a large Chinese cohort: A cross-sectional study",
    authors: "Wang Z, Hu X, Mo H, Shen M, et al.",
    journal: "JAAD international",
    year: 2025,
    date: "February 2025",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41399671/",
    doiUrl: "https://doi.org/10.1016/j.jdin.2025.09.020",
  },
  {
    pmid: "41061983",
    title: "Measurement of the severity related to cutaneous neurofibromas in neurofibromatosis type 1: Development and validation of the Nef-ASI",
    authors: "Fertitta L, Jannic A, Bergqvist C, Delique V, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2026,
    date: "February 2026",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41061983/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2025.10.025",
    image: "/images/recent-work/nef-asi.jpg",
    imageAlt: "Bland–Altman plot comparing cutaneous neurofibroma measurements across raters.",
    featured: true,
  },
  {
    pmid: "41022330",
    title: "The P2X7-NLRP3 inflammasome inhibitor AZD9056 has no significant effect on hidradenitis suppurativa clinical disease activity but restores cytokine production in peripheral blood mononuclear cells: Results of a phase 2 trial",
    authors: "Kilgour JM, Landy H, Kimball AB, Resnik BI, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2026,
    date: "January 2026",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41022330/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2025.09.079",
  },
  {
    pmid: "41350049",
    title: "A Response to the Letter to the Editor: Refining Risk and Redefining Stage: Hidden Implications of BAP1-Mutant Mesothelioma Shiuan-Chih Chen, MD, PhD; Yuan-Ti Lee, MD, PhD",
    authors: "Carbone M, Minaai M, Kittaneh M, Krausz T, et al.",
    journal: "Journal of thoracic oncology : official publication of the International Association for the Study of Lung Cancer",
    year: 2025,
    date: "December 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/41350049/",
    doiUrl: "https://doi.org/10.1016/j.jtho.2025.07.124",
  },
  {
    pmid: "40582407",
    title: "Clinical and Pathologic Phenotyping of Mesotheliomas Developing in Carriers of Germline BAP1 Mutations",
    authors: "Carbone M, Minaai M, Kittaneh M, Krausz T, et al.",
    journal: "Journal of thoracic oncology : official publication of the International Association for the Study of Lung Cancer",
    year: 2025,
    date: "November 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40582407/",
    doiUrl: "https://doi.org/10.1016/j.jtho.2025.06.020",
  },
  {
    pmid: "40494346",
    title: "Neuroendocrine cells orchestrate regeneration through Desert hedgehog signaling",
    authors: "Kong W, Lu WJ, Dubey M, Suryawanshi RK, et al.",
    journal: "Cell",
    year: 2025,
    date: "September 2025",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40494346/",
    doiUrl: "https://doi.org/10.1016/j.cell.2025.05.012",
  },
  {
    pmid: "40607077",
    title: "Biosimilars in dermatology: New opportunities and obstacles",
    authors: "Leeolou MC, Jia JL, Sarin KY",
    journal: "JAAD international",
    year: 2025,
    date: "August 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40607077/",
    doiUrl: "https://doi.org/10.1016/j.jdin.2025.05.003",
  },
  {
    pmid: "40064376",
    title: "Navigating patient access to treatment: A focus on pharmaceutical drug samples",
    authors: "Leeolou MC, Jia JL, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2025,
    date: "July 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40064376/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2025.01.102",
  },
  {
    pmid: "40272833",
    title: "Patient-Centered Research Through Artificial Intelligence to Identify Priorities in Cancer Care",
    authors: "Kim J, Chen ML, Rezaei SJ, Ramirez-Posada M, et al.",
    journal: "JAMA oncology",
    year: 2025,
    date: "June 2025",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40272833/",
    doiUrl: "https://doi.org/10.1001/jamaoncol.2025.0694",
  },
  {
    pmid: "40117305",
    title: "Age-dependent cytokine surge in blood precedes cancer diagnosis",
    authors: "Chen G, Mohsin A, Zheng H, Rosenberg-Hasson Y, et al.",
    journal: "Proceedings of the National Academy of Sciences of the United States of America",
    year: 2025,
    date: "March 2025",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40117305/",
    doiUrl: "https://doi.org/10.1073/pnas.2420502122",
  },
  {
    pmid: "39937150",
    title: "Barriers to Health Care Affordability Among Parents of Children with Atopic Dermatitis",
    authors: "Youn CG, Bae GH, Honari G, Chen JK, et al.",
    journal: "Dermatitis : contact, atopic, occupational, drug",
    year: 2025,
    date: "March 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39937150/",
    doiUrl: "https://doi.org/10.1089/derm.2024.0248",
  },
  {
    pmid: "39521139",
    title: "When savings fall short: Drug coupons for generic prescriptions do not always result in savings for patients",
    authors: "Leeolou MC, Jia JL, Pham D, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2025,
    date: "March 2025",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39521139/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2024.10.062",
  },
  {
    pmid: "40060632",
    title: "Dissection of Gαs and Hedgehog signaling crosstalk reveals therapeutic opportunities to target adenosine receptor 2b in Hedgehog-dependent tumors",
    authors: "Krantz S, Bell B, Lund K, Parra NS, et al.",
    journal: "bioRxiv : the preprint server for biology",
    year: 2025,
    date: "February 2025",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/40060632/",
    doiUrl: "https://doi.org/10.1101/2025.02.21.639530",
  },
  {
    pmid: "39553486",
    title: "Identification of activating hotspot mutations in acrochordons through next-generation sequencing",
    authors: "Jia JL, Wang JY, Chan WH, Lanoue J, et al.",
    journal: "JAAD international",
    year: 2024,
    date: "February 2024",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39553486/",
    doiUrl: "https://doi.org/10.1016/j.jdin.2024.08.011",
  },
  {
    pmid: "39279150",
    title: "TLR7/8 Activation in Immune Cells and Muscle by RNA-Containing Immune Complexes: Role in Inflammation and the Pathogenesis of Myositis",
    authors: "Wu Y, Deshpande A, Geraci N, Budde P, et al.",
    journal: "Arthritis & rheumatology (Hoboken, N.J.)",
    year: 2025,
    date: "February 2025",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39279150/",
    doiUrl: "https://doi.org/10.1002/art.42989",
  },
  {
    pmid: "39287419",
    title: "Multiomics Profiling Distinguishes Sebaceous Carcinoma from Benign Sebaceous Neoplasms and Provides Insight into the Genetic Evolution of Sebaceous Carcinogenesis",
    authors: "Starrett GJ, Baikie BC, Stoff BK, Grossniklaus HE, et al.",
    journal: "Clinical cancer research : an official journal of the American Association for Cancer Research",
    year: 2024,
    date: "November 2024",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39287419/",
    doiUrl: "https://doi.org/10.1158/1078-0432.CCR-24-1327",
  },
  {
    pmid: "39196570",
    title: "Cutaneous Neurofibromas and Quality of Life in Adults With Neurofibromatosis Type 1",
    authors: "Lin MJ, Yao H, Vera K, Patel E, et al.",
    journal: "JAMA dermatology",
    year: 2024,
    date: "October 2024",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39196570/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2024.2912",
  },
  {
    pmid: "38975641",
    title: "Analysing common topics of secure patient messages in hidradenitis suppurativa: a text-embedding and natural language-processing approach",
    authors: "Chen ML, Kim J, Naik HB, Aleshin MA, et al.",
    journal: "The British journal of dermatology",
    year: 2024,
    date: "September 2024",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38975641/",
    doiUrl: "https://doi.org/10.1093/bjd/ljae222",
  },
  {
    pmid: "38635917",
    title: "Filling the prescription gap: the value of community support in psoriasis management",
    authors: "Leeolou MC, Sarin KY, Fiorentino DF",
    journal: "The British journal of dermatology",
    year: 2024,
    date: "August 2024",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38635917/",
    doiUrl: "https://doi.org/10.1093/bjd/ljae168",
  },
  {
    pmid: "38990952",
    title: "Germline BARD1 variants predispose to mesothelioma by impairing DNA repair and calcium signaling",
    authors: "Novelli F, Yoshikawa Y, Vitto VAM, Modesti L, et al.",
    journal: "Proceedings of the National Academy of Sciences of the United States of America",
    year: 2024,
    date: "July 2024",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38990952/",
    doiUrl: "https://doi.org/10.1073/pnas.2405231121",
  },
  {
    pmid: "38776098",
    title: "Parental E-Cigarette Use and Pediatric Atopic Dermatitis",
    authors: "Youn GM, Sarin KY, Chiou AS, Chen JK, et al.",
    journal: "JAMA dermatology",
    year: 2024,
    date: "July 2024",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38776098/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2024.1283",
  },
  {
    pmid: "38691597",
    title: "Effect of NFX-179 MEK inhibitor on cutaneous neurofibromas in persons with neurofibromatosis type 1",
    authors: "Sarin KY, Bradshaw M, O'Mara C, Shahryari J, et al.",
    journal: "Science advances",
    year: 2024,
    date: "May 2024",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38691597/",
    doiUrl: "https://doi.org/10.1126/sciadv.adk4946",
  },
  {
    pmid: "38598626",
    title: "Noninvasive virtual biopsy using micro-registered optical coherence tomography (OCT) in human subjects",
    authors: "Winetraub Y, Van Vleck A, Yuan E, Terem I, et al.",
    journal: "Science advances",
    year: 2024,
    date: "April 2024",
    researchArea: "Non-Invasive Imaging",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38598626/",
    doiUrl: "https://doi.org/10.1126/sciadv.adi5794",
  },
  {
    pmid: "38456511",
    title: "Impaired innate and adaptive immune responses to BNT162b2 SARS-CoV-2 vaccination in systemic lupus erythematosus",
    authors: "Sarin KY, Zheng H, Chaichian Y, Arunachalam PS, et al.",
    journal: "JCI insight",
    year: 2024,
    date: "March 2024",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38456511/",
    doiUrl: "https://doi.org/10.1172/jci.insight.176556",
  },
  {
    pmid: "37598867",
    title: "Cross-Comparison of Inflammatory Skin Disease Transcriptomics Identifies PTEN as a Pathogenic Disease Classifier in Cutaneous Lupus Erythematosus",
    authors: "Aevermann BD, Di Domizio J, Olah P, Saidoune F, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2024,
    date: "February 2024",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37598867/",
    doiUrl: "https://doi.org/10.1016/j.jid.2023.06.211",
  },
  {
    pmid: "37269078",
    title: "Perspectives of adolescents with neurofibromatosis 1 and cutaneous neurofibromas: Implications for clinical trials",
    authors: "Cannon A, Sarin KY, Petersen AK, Pichard DC, et al.",
    journal: "Clinical trials (London, England)",
    year: 2024,
    date: "February 2024",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37269078/",
    doiUrl: "https://doi.org/10.1177/17407745231178839",
  },
  {
    pmid: "38123358",
    title: "Toward risk stratification and personalized therapy for neurofibromas in neurofibromatosis type 1",
    authors: "Romo CG, Sarin KY, Blakeley JO",
    journal: "The British journal of dermatology",
    year: 2024,
    date: "January 2024",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38123358/",
    doiUrl: "https://doi.org/10.1093/bjd/ljad452",
  },
  {
    pmid: "37877514",
    title: "A core outcome domain set to assess cutaneous neurofibromas related to neurofibromatosis type 1 in clinical trials",
    authors: "Fertitta L, Bergqvist C, Sarin KY, Plotkin SR, et al.",
    journal: "The British journal of dermatology",
    year: 2024,
    date: "January 2024",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37877514/",
    doiUrl: "https://doi.org/10.1093/bjd/ljad397",
  },
  {
    pmid: "39137473",
    title: "Unveiling the genetic landscape of hereditary melanoma: From susceptibility to surveillance",
    authors: "Zheng C, Sarin KY",
    journal: "Cancer treatment and research communications",
    year: 2024,
    date: "2024",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39137473/",
    doiUrl: "https://doi.org/10.1016/j.ctarc.2024.100837",
  },
  {
    pmid: "37149083",
    title: "cNF-Skindex in Adults Living with Neurofibromatosis 1: Severity Strata in France and Validation in United States Adults",
    authors: "Fertitta L, Sarin KY, Bergqvist C, Patel E, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2023,
    date: "November 2023",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37149083/",
    doiUrl: "https://doi.org/10.1016/j.jid.2023.04.014",
  },
  {
    pmid: "37820007",
    title: "Development of a MEK inhibitor, NFX-179, as a chemoprevention agent for squamous cell carcinoma",
    authors: "Sarin KY, Kincaid J, Sell B, Shahryari J, et al.",
    journal: "Science translational medicine",
    year: 2023,
    date: "October 2023",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37820007/",
    doiUrl: "https://doi.org/10.1126/scitranslmed.ade1844",
  },
  {
    pmid: "37096447",
    title: "The Type I Interferon Signature Reflects Multiple Phenotypic and Activity Measures in Dermatomyositis",
    authors: "Tabata MM, Hodgkinson LM, Wu TT, Li S, et al.",
    journal: "Arthritis & rheumatology (Hoboken, N.J.)",
    year: 2023,
    date: "October 2023",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37096447/",
    doiUrl: "https://doi.org/10.1002/art.42526",
  },
  {
    pmid: "37274386",
    title: "Hidradenitis suppurativa and Ehlers-Danlos syndrome: A case-control study",
    authors: "Hua VJ, Li S, Sarin KY, Aleshin M",
    journal: "JAAD international",
    year: 2023,
    date: "September 2023",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37274386/",
    doiUrl: "https://doi.org/10.1016/j.jdin.2023.03.008",
  },
  {
    pmid: "37354152",
    title: "A Call for Discovery and Therapeutic Development for Cutaneous Neurofibromas",
    authors: "Blakeley JO, Le LQ, Lee SY, Ly I, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2023,
    date: "August 2023",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37354152/",
    doiUrl: "https://doi.org/10.1016/j.jid.2022.11.027",
  },
  {
    pmid: "37245145",
    title: "RAS Signaling Gone Awry in the Skin: The Complex Role of RAS in Cutaneous Neurofibroma Pathogenesis, Emerging Biological Insights",
    authors: "Rhodes SD, McCormick F, Cagan RL, Bakker A, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2023,
    date: "August 2023",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37245145/",
    doiUrl: "https://doi.org/10.1016/j.jid.2023.01.043",
  },
  {
    pmid: "37286893",
    title: "Advances in cutaneous squamous cell carcinoma",
    authors: "Winge MCG, Kellman LN, Guo K, Tang JY, et al.",
    journal: "Nature reviews. Cancer",
    year: 2023,
    date: "July 2023",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37286893/",
    doiUrl: "https://doi.org/10.1038/s41568-023-00583-5",
  },
  {
    pmid: "36775101",
    title: "Prevalence of allergic contact dermatitis following patch testing in patients with atopic dermatitis: A retrospective United States claims-based study",
    authors: "Qian MF, Li S, Honari G, Sarin KY, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2023,
    date: "June 2023",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36775101/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2022.12.051",
  },
  {
    pmid: "30287320",
    title: "Association of multiple primary melanomas with malignancy risk: A population-based analysis of entries from the Surveillance, Epidemiology, and End Results program database during 1973-2014",
    authors: "Cai ED, Swetter SM, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2023,
    date: "May 2023",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30287320/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2018.09.027",
  },
  {
    pmid: "36876222",
    title: "Modulation of Inflammatory Proteins in Serum May Reflect Cutaneous Immune Responses in Cancer Immunotherapy",
    authors: "Han J, Correa da Rosa J, Agarwal A, Owji S, et al.",
    journal: "JID innovations : skin science from molecules to population health",
    year: 2023,
    date: "March 2023",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36876222/",
    doiUrl: "https://doi.org/10.1016/j.xjidi.2022.100179",
  },
  {
    pmid: "36745734",
    title: "Rapid Cellular-Resolution Skin Imaging with Optical Coherence Tomography Using All-Glass Multifocal Metasurfaces",
    authors: "Zhao J, Van Vleck A, Winetraub Y, Du L, et al.",
    journal: "ACS nano",
    year: 2023,
    date: "February 2023",
    researchArea: "Non-Invasive Imaging",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36745734/",
    doiUrl: "https://doi.org/10.1021/acsnano.2c09542",
  },
  {
    pmid: "35728719",
    title: "Tuberous sclerosis and risk of skin cancer: A nationwide cohort study in the United States",
    authors: "Trinh P, Li S, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2023,
    date: "February 2023",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/35728719/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2022.06.029",
  },
  {
    pmid: "36473848",
    title: "LY6D marks pre-existing resistant basosquamous tumor subpopulations",
    authors: "Haensel D, Gaddam S, Li NY, Gonzalez F, et al.",
    journal: "Nature communications",
    year: 2022,
    date: "December 2022",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36473848/",
    doiUrl: "https://doi.org/10.1038/s41467-022-35020-y",
  },
  {
    pmid: "36041554",
    title: "Sociodemographic disparities in patch testing for commercially insured patients with dermatitis: A retrospective analysis of administrative claims data",
    authors: "Qian MF, Li S, Honari G, Sarin KY, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2022,
    date: "December 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36041554/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2022.08.041",
  },
  {
    pmid: "36255394",
    title: "Assessment of Comorbidities Associated With Allergic Contact Dermatitis in the United States: A Retrospective Claims-Based Study",
    authors: "Hua VJ, Li S, Qian MF, Honari G, et al.",
    journal: "Dermatitis : contact, atopic, occupational, drug",
    year: 2022,
    date: "November 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36255394/",
    doiUrl: "https://doi.org/10.1097/DER.0000000000000964",
  },
  {
    pmid: "35831023",
    title: "ERK2 MAP kinase regulates SUFU binding by multisite phosphorylation of GLI1",
    authors: "Bardwell AJ, Wu B, Sarin KY, Waterman ML, et al.",
    journal: "Life science alliance",
    year: 2022,
    date: "November 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/35831023/",
    doiUrl: "https://doi.org/10.26508/lsa.202101353",
  },
  {
    pmid: "36001333",
    title: "Neurofibromatosis Type 1 and Risk of Skin Cancer",
    authors: "Trinh P, Li S, Sarin KY",
    journal: "JAMA dermatology",
    year: 2022,
    date: "October 2022",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36001333/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2022.3083",
  },
  {
    pmid: "35941936",
    title: "Partnering with a senior living community to optimise teledermatology via full body skin screening during the COVID-19 pandemic: A pilot programme",
    authors: "Trinh P, Yekrang K, Phung M, Pugliese S, et al.",
    journal: "Skin health and disease",
    year: 2022,
    date: "September 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/35941936/",
    doiUrl: "https://doi.org/10.1002/ski2.141",
  },
  {
    pmid: "35551965",
    title: "Development of a core outcome set for basal cell carcinoma",
    authors: "Schlessinger DI, Reynolds KA, Dirr MA, Ibrahim SA, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2022,
    date: "September 2022",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/35551965/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2022.04.059",
  },
  {
    pmid: "37283722",
    title: "Flexible method for generating needle-shaped beams and its application in optical coherence tomography",
    authors: "Zhao J, Winetraub Y, DU L, VAN Vleck A, et al.",
    journal: "Optica",
    year: 2022,
    date: "August 2022",
    researchArea: "Non-Invasive Imaging",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37283722/",
    doiUrl: "https://doi.org/10.1364/optica.456894",
  },
  {
    pmid: "34058279",
    title: "Prevalence of potentially allergenic ingredients in products labeled for eczema care",
    authors: "Schwartz BL, Honari G, Chiou AS, Ko J, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2022,
    date: "June 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34058279/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2021.05.038",
  },
  {
    pmid: "34536484",
    title: "Transcriptomic Repositioning Analysis Identifies mTOR Inhibitor as Potential Therapy for Epidermolysis Bullosa Simplex",
    authors: "Lee GH, Lekwuttikarn R, Tafoya E, Martin M, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2022,
    date: "February 2022",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34536484/",
    doiUrl: "https://doi.org/10.1016/j.jid.2021.07.170",
  },
  {
    pmid: "34787644",
    title: "Treatment of Cutaneous Squamous Cell Carcinoma With the Topical Histone Deacetylase Inhibitor Remetinostat",
    authors: "Kilgour JM, Shah A, Eichstadt S, Bailey I, et al.",
    journal: "JAMA dermatology",
    year: 2022,
    date: "January 2022",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34787644/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2021.4549",
  },
  {
    pmid: "34546979",
    title: "Characterization of comorbidity heterogeneity among 13,667 patients with hidradenitis suppurativa",
    authors: "Hua VJ, Kilgour JM, Cho HG, Li S, et al.",
    journal: "JCI insight",
    year: 2021,
    date: "November 2021",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34546979/",
    doiUrl: "https://doi.org/10.1172/jci.insight.151872",
  },
  {
    pmid: "33476728",
    title: "Direct-to-consumer genetic risk scoring for melanoma improves adherence to sun-protective behaviors among increased-risk groups: Results from a prospective United States cohort study",
    authors: "Hu X, Kilgour JM, Fogel AL, Jia JL, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2021,
    date: "October 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/33476728/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2021.01.042",
  },
  {
    pmid: "34362809",
    title: "Phase II Open-Label, Single-Arm Trial to Investigate the Efficacy and Safety of Topical Remetinostat Gel in Patients with Basal Cell Carcinoma",
    authors: "Kilgour JM, Shah A, Urman NM, Eichstadt S, et al.",
    journal: "Clinical cancer research : an official journal of the American Association for Cancer Research",
    year: 2021,
    date: "September 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34362809/",
    doiUrl: "https://doi.org/10.1158/1078-0432.CCR-21-0560",
  },
  {
    pmid: "34230199",
    title: "Status and Recommendations for Incorporating Biomarkers for Cutaneous Neurofibromas Into Clinical Research",
    authors: "Wallis D, Stemmer-Rachamimov A, Adsit S, Korf B, et al.",
    journal: "Neurology",
    year: 2021,
    date: "August 2021",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34230199/",
    doiUrl: "https://doi.org/10.1212/WNL.0000000000012426",
  },
  {
    pmid: "34359772",
    title: "Review of the Molecular Genetics of Basal Cell Carcinoma; Inherited Susceptibility, Somatic Mutations, and Targeted Therapeutics",
    authors: "Kilgour JM, Jia JL, Sarin KY",
    journal: "Cancers",
    year: 2021,
    date: "July 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34359772/",
    doiUrl: "https://doi.org/10.3390/cancers13153870",
  },
  {
    pmid: "34076667",
    title: "Dermatology Advances Into an Era of Precision Medicine",
    authors: "Wang JY, Sarin KY",
    journal: "JAMA dermatology",
    year: 2021,
    date: "July 2021",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34076667/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2021.0024",
  },
  {
    pmid: "33165076",
    title: "Patient Crowdfunding for the Treatment of Cutaneous Malignancies",
    authors: "Jia JL, Mills DE, Urman NM, Sarin KY",
    journal: "Dermatologic surgery : official publication for American Society for Dermatologic Surgery [et al.]",
    year: 2021,
    date: "July 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/33165076/",
    doiUrl: "https://doi.org/10.1097/DSS.0000000000002866",
  },
  {
    pmid: "34409370",
    title: "Hidradenitis suppurativa in patients of color is associated with increased disease severity and healthcare utilization: A retrospective analysis of 2 U.S. cohorts",
    authors: "Kilgour JM, Li S, Sarin KY",
    journal: "JAAD international",
    year: 2021,
    date: "June 2021",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34409370/",
    doiUrl: "https://doi.org/10.1016/j.jdin.2021.01.007",
  },
  {
    pmid: "32735972",
    title: "Prevalence and risk factors for high-frequency basal cell carcinoma in the United States",
    authors: "Chiang A, Solis DC, Rogers H, Sohn GK, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2021,
    date: "May 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32735972/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2020.07.088",
  },
  {
    pmid: "32389713",
    title: "Fitzpatrick phototype disparities in identification of cutaneous malignancies by Google Reverse Image",
    authors: "Jia JL, Wang JY, Mills DE, Shen A, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2021,
    date: "May 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32389713/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2020.05.005",
  },
  {
    pmid: "33602785",
    title: "Loss-of-Function Variants in the Tumor-Suppressor Gene PTPN14 Confer Increased Cancer Risk",
    authors: "Olafsdottir T, Stacey SN, Sveinbjornsson G, Thorleifsson G, et al.",
    journal: "Cancer research",
    year: 2021,
    date: "April 2021",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/33602785/",
    doiUrl: "https://doi.org/10.1158/0008-5472.CAN-20-3065",
  },
  {
    pmid: "32781178",
    title: "A phase 2, double-blinded, placebo-controlled trial of toll-like receptor 7/8/9 antagonist, IMO-8400, in dermatomyositis",
    authors: "Kim YJ, Schiopu E, Dankó K, Mozaffar T, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2021,
    date: "April 2021",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32781178/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2020.07.122",
  },
  {
    pmid: "33033234",
    title: "AP-1 and TGFß cooperativity drives non-canonical Hedgehog signaling in resistant basal cell carcinoma",
    authors: "Yao CD, Haensel D, Gaddam S, Patel T, et al.",
    journal: "Nature communications",
    year: 2020,
    date: "October 2020",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/33033234/",
    doiUrl: "https://doi.org/10.1038/s41467-020-18762-5",
  },
  {
    pmid: "32814709",
    title: "Phenotypic heterogeneity of neurofibromatosis type 1 in a large international registry",
    authors: "Tabata MM, Li S, Knight P, Bakker A, et al.",
    journal: "JCI insight",
    year: 2020,
    date: "August 2020",
    researchArea: "Neurofibromatosis",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32814709/",
    doiUrl: "https://doi.org/10.1172/jci.insight.136262",
  },
  {
    pmid: "31836559",
    title: "Comparing online engagement and academic impact of dermatology research: An Altmetric Attention Score and PlumX Metrics analysis",
    authors: "Jia JL, Nguyen B, Mills DE, Polin DJ, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2020,
    date: "August 2020",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31836559/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2019.12.003",
  },
  {
    pmid: "32266730",
    title: "Gamification improves melanoma visual identification among high school students: Results from a randomized study",
    authors: "Jia JL, Shen A, Tabata MM, Sarin KY",
    journal: "Pediatric dermatology",
    year: 2020,
    date: "July 2020",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32266730/",
    doiUrl: "https://doi.org/10.1111/pde.14158",
  },
  {
    pmid: "32186684",
    title: "Sexual and Gender Minority Curricula Within US Dermatology Residency Programs",
    authors: "Jia JL, Nord KM, Sarin KY, Linos E, et al.",
    journal: "JAMA dermatology",
    year: 2020,
    date: "May 2020",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32186684/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2020.0113",
  },
  {
    pmid: "32115137",
    title: "Ways to Improve Care for LGBT Patients in Dermatology Clinics",
    authors: "Jia JL, Polin DJ, Sarin KY",
    journal: "Dermatologic clinics",
    year: 2020,
    date: "April 2020",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32115137/",
    doiUrl: "https://doi.org/10.1016/j.det.2019.10.012",
  },
  {
    pmid: "31449904",
    title: "Hyperhidrosis affects quality of life in hidradenitis suppurativa: A prospective analysis",
    authors: "Hua VJ, Kuo KY, Cho HG, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2020,
    date: "March 2020",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31449904/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2019.08.046",
  },
  {
    pmid: "32041948",
    title: "Genome-wide meta-analysis identifies eight new susceptibility loci for cutaneous squamous cell carcinoma",
    authors: "Sarin KY, Lin Y, Daneshjou R, Ziyatdinov A, et al.",
    journal: "Nature communications",
    year: 2020,
    date: "February 2020",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32041948/",
    doiUrl: "https://doi.org/10.1038/s41467-020-14594-5",
  },
  {
    pmid: "32024946",
    title: "Angular compounding for speckle reduction in optical coherence tomography using geometric image registration algorithm and digital focusing",
    authors: "Zhao J, Winetraub Y, Yuan E, Chan WH, et al.",
    journal: "Scientific reports",
    year: 2020,
    date: "February 2020",
    researchArea: "Non-Invasive Imaging",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32024946/",
    doiUrl: "https://doi.org/10.1038/s41598-020-58454-0",
  },
  {
    pmid: "31920360",
    title: "From Clinical Phenotype to Genotypic Modelling: Incidence and Prevalence of Recessive Dystrophic Epidermolysis Bullosa (RDEB)",
    authors: "Eichstadt S, Tang JY, Solis DC, Siprashvili Z, et al.",
    journal: "Clinical, cosmetic and investigational dermatology",
    year: 2019,
    date: "2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31920360/",
    doiUrl: "https://doi.org/10.2147/CCID.S232547",
  },
  {
    pmid: "31468562",
    title: "Assessment of readability and content of patient-initiated google search results for epidermolysis bullosa",
    authors: "Jia JL, Nguyen B, Sarin KY",
    journal: "Pediatric dermatology",
    year: 2019,
    date: "November 2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31468562/",
    doiUrl: "https://doi.org/10.1111/pde.13975",
  },
  {
    pmid: "31330148",
    title: "Response to Shih et al",
    authors: "Chiang A, Batra P, Sarin KY",
    journal: "The Journal of investigative dermatology",
    year: 2019,
    date: "November 2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31330148/",
    doiUrl: "https://doi.org/10.1016/j.jid.2019.06.139",
  },
  {
    pmid: "31207229",
    title: "Genetic Mutations Underlying Phenotypic Plasticity in Basosquamous Carcinoma",
    authors: "Chiang A, Tan CZ, Kuonen F, Hodgkinson LM, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2019,
    date: "November 2019",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31207229/",
    doiUrl: "https://doi.org/10.1016/j.jid.2019.03.1163",
  },
  {
    pmid: "31359002",
    title: "Clonal replacement of tumor-specific T cells following PD-1 blockade",
    authors: "Yost KE, Satpathy AT, Wells DK, Qi Y, et al.",
    journal: "Nature medicine",
    year: 2019,
    date: "August 2019",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31359002/",
    doiUrl: "https://doi.org/10.1038/s41591-019-0522-3",
  },
  {
    pmid: "30707899",
    title: "Loss of Primary Cilia Drives Switching from Hedgehog to Ras/MAPK Pathway in Resistant Basal Cell Carcinoma",
    authors: "Kuonen F, Huskey NE, Shankar G, Jaju P, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2019,
    date: "July 2019",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30707899/",
    doiUrl: "https://doi.org/10.1016/j.jid.2018.11.035",
  },
  {
    pmid: "31162134",
    title: "Early Detection of Adverse Drug Reactions in Social Health Networks: A Natural Language Processing Pipeline for Signal Detection",
    authors: "Nikfarjam A, Ransohoff JD, Callahan A, Jones E, et al.",
    journal: "JMIR public health and surveillance",
    year: 2019,
    date: "June 2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31162134/",
    doiUrl: "https://doi.org/10.2196/11264",
  },
  {
    pmid: "30672662",
    title: "Biomarker discovery analysis: Alterations in p14, p16, p53, and BAP1 expression in nevi, cutaneous melanoma, and metastatic melanoma",
    authors: "Sargen MR, Cloutier JM, Sarin KY, Rieger KE, et al.",
    journal: "Pigment cell & melanoma research",
    year: 2019,
    date: "May 2019",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30672662/",
    doiUrl: "https://doi.org/10.1111/pcmr.12768",
  },
  {
    pmid: "30947262",
    title: "Alterations of the MEK/ERK, BMP, and Wnt/β-catenin pathways detected in the blood of individuals with lymphatic malformations",
    authors: "Kim T, Tafoya E, Chelliah MP, Lekwuttikarn R, et al.",
    journal: "PloS one",
    year: 2019,
    date: "2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30947262/",
    doiUrl: "https://doi.org/10.1371/journal.pone.0213872",
  },
  {
    pmid: "31051025",
    title: "Emerging technologies for health information in dermatology: opportunities and drawbacks of web-based searches, social media, mobile applications, and direct-to-consumer genetic testing in patient care",
    authors: "Jia JL, Polin DJ, Sarin KY",
    journal: "Seminars in cutaneous medicine and surgery",
    year: 2019,
    date: "March 2019",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31051025/",
    doiUrl: "https://doi.org/10.12788/j.sder.2019.002",
  },
  {
    pmid: "29758283",
    title: "TGFβ, Fibronectin and Integrin α5β1 Promote Invasion in Basal Cell Carcinoma",
    authors: "Kuonen F, Surbeck I, Sarin KY, Dontenwill M, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2018,
    date: "November 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29758283/",
    doiUrl: "https://doi.org/10.1016/j.jid.2018.04.029",
  },
  {
    pmid: "30376426",
    title: "A Subset of Mesotheliomas With Improved Survival Occurring in Carriers of BAP1 and Other Germline Mutations",
    authors: "Pastorino S, Yoshikawa Y, Pass HI, Emi M, et al.",
    journal: "Journal of clinical oncology : official journal of the American Society of Clinical Oncology",
    year: 2018,
    date: "October 2018",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30376426/",
    doiUrl: "https://doi.org/10.1200/JCO.2018.79.0352",
  },
  {
    pmid: "29580869",
    title: "Inverse Relationship between Vitiligo-Related Genes and Skin Cancer Risk",
    authors: "Wu W, Amos CI, Lee JE, Wei Q, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2018,
    date: "September 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29580869/",
    doiUrl: "https://doi.org/10.1016/j.jid.2018.03.1511",
  },
  {
    pmid: "30089731",
    title: "Frequent basal cell cancer development is a clinical marker for inherited cancer susceptibility",
    authors: "Cho HG, Kuo KY, Li S, Bailey I, et al.",
    journal: "JCI insight",
    year: 2018,
    date: "August 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30089731/",
    doiUrl: "https://doi.org/10.1172/jci.insight.122744",
  },
  {
    pmid: "29499294",
    title: "Melanoma risk prediction using a multilocus genetic risk score in the Women's Health Initiative cohort",
    authors: "Cho HG, Ransohoff KJ, Yang L, Hedlin H, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2018,
    date: "July 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29499294/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2018.02.052",
  },
  {
    pmid: "29247661",
    title: "Identification of Atorvastatin for Moderate to Severe Hidradenitis through Drug Repositioning Using Public Gene Expression Datasets",
    authors: "Kuo KY, Cho HG, Sarin KY",
    journal: "The Journal of investigative dermatology",
    year: 2018,
    date: "May 2018",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29247661/",
    doiUrl: "https://doi.org/10.1016/j.jid.2017.12.002",
  },
  {
    pmid: "29111235",
    title: "Genomic Stability in Syndromic Basal Cell Carcinoma",
    authors: "Chiang A, Jaju PD, Batra P, Rezaee M, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2018,
    date: "May 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29111235/",
    doiUrl: "https://doi.org/10.1016/j.jid.2017.09.048",
  },
  {
    pmid: "29494731",
    title: "Detecting Chemotherapeutic Skin Adverse Reactions in Social Health Networks Using Deep Learning",
    authors: "Ransohoff JD, Nikfarjam A, Jones E, Loew B, et al.",
    journal: "JAMA oncology",
    year: 2018,
    date: "April 2018",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29494731/",
    doiUrl: "https://doi.org/10.1001/jamaoncol.2017.5688",
  },
  {
    pmid: "29400712",
    title: "Noncanonical hedgehog pathway activation through SRF-MKL1 promotes drug resistance in basal cell carcinomas",
    authors: "Whitson RJ, Lee A, Urman NM, Mirza A, et al.",
    journal: "Nature medicine",
    year: 2018,
    date: "March 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29400712/",
    doiUrl: "https://doi.org/10.1038/nm.4476",
  },
  {
    pmid: "28989107",
    title: "Azathioprine and risk of multiple keratinocyte cancers",
    authors: "Cho HG, Kuo KY, Xiao K, Batra P, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2018,
    date: "January 2018",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28989107/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2017.09.063",
  },
  {
    pmid: "29093271",
    title: "Combined inhibition of atypical PKC and histone deacetylase 1 is cooperative in basal cell carcinoma treatment",
    authors: "Mirza AN, Fry MA, Urman NM, Atwood SX, et al.",
    journal: "JCI insight",
    year: 2017,
    date: "November 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29093271/",
    doiUrl: "https://doi.org/10.1172/jci.insight.97071",
  },
  {
    pmid: "28510302",
    title: "Association study of genetic variation in DNA repair pathway genes and risk of basal cell carcinoma",
    authors: "Lin Y, Chahal HS, Wu W, Cho HG, et al.",
    journal: "International journal of cancer",
    year: 2017,
    date: "September 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28510302/",
    doiUrl: "https://doi.org/10.1002/ijc.30786",
  },
  {
    pmid: "28525403",
    title: "Genetic diseases associated with an increased risk of skin cancer development in childhood",
    authors: "Fogel AL, Sarin KY, Teng JMC",
    journal: "Current opinion in pediatrics",
    year: 2017,
    date: "August 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28525403/",
    doiUrl: "https://doi.org/10.1097/MOP.0000000000000514",
  },
  {
    pmid: "28392289",
    title: "Correlates of multiple basal cell carcinoma in a retrospective cohort study: Sex, histologic subtypes, and anatomic distribution",
    authors: "Kuo KY, Batra P, Cho HG, Li S, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2017,
    date: "August 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28392289/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2017.02.047",
  },
  {
    pmid: "28347698",
    title: "Postzygotic Mutations in Beta-Actin Are Associated with Becker's Nevus and Becker's Nevus Syndrome",
    authors: "Cai ED, Sun BK, Chiang A, Rogers A, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2017,
    date: "August 2017",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28347698/",
    doiUrl: "https://doi.org/10.1016/j.jid.2017.03.017",
  },
  {
    pmid: "28377414",
    title: "Diagnostic Distinction of Malignant Melanoma and Benign Nevi by a Gene Expression Signature and Correlation to Clinical Outcomes",
    authors: "Ko JS, Matharoo-Ball B, Billings SD, Thomson BJ, et al.",
    journal: "Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology",
    year: 2017,
    date: "July 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28377414/",
    doiUrl: "https://doi.org/10.1158/1055-9965.EPI-16-0958",
  },
  {
    pmid: "28666115",
    title: "IFNγ-Dependent Tissue-Immune Homeostasis Is Co-opted in the Tumor Microenvironment",
    authors: "Nirschl CJ, Suárez-Fariñas M, Izar B, Prakadan S, et al.",
    journal: "Cell",
    year: 2017,
    date: "June 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28666115/",
    doiUrl: "https://doi.org/10.1016/j.cell.2017.06.016",
  },
  {
    pmid: "28177523",
    title: "Association between genetic variation within vitamin D receptor-DNA binding sites and risk of basal cell carcinoma",
    authors: "Lin Y, Chahal HS, Wu W, Cho HG, et al.",
    journal: "International journal of cancer",
    year: 2017,
    date: "May 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28177523/",
    doiUrl: "https://doi.org/10.1002/ijc.30634",
  },
  {
    pmid: "28087134",
    title: "Factors influencing and modifying the decision to pursue genetic testing for skin cancer risk",
    authors: "Fogel AL, Jaju PD, Li S, Halpern-Felsher B, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2017,
    date: "May 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28087134/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2016.11.050",
  },
  {
    pmid: "28212542",
    title: "Two-stage genome-wide association study identifies a novel susceptibility locus associated with melanoma",
    authors: "Ransohoff KJ, Wu W, Cho HG, Chahal HC, et al.",
    journal: "Oncotarget",
    year: 2017,
    date: "March 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28212542/",
    doiUrl: "https://doi.org/10.18632/oncotarget.15230",
  },
  {
    pmid: "28089000",
    title: "Incidence ratio of basal cell carcinoma to squamous cell carcinoma equalizes with age",
    authors: "Chahal HS, Rieger KE, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2017,
    date: "February 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28089000/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2016.08.019",
  },
  {
    pmid: "27813222",
    title: "Invasive Melanoma in a Patient with Congenital Ichthyosiform Erythroderma",
    authors: "Jaju P, Novoa RA, Swetter SM, Sarin KY",
    journal: "Pediatric dermatology",
    year: 2017,
    date: "January 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27813222/",
    doiUrl: "https://doi.org/10.1111/pde.13012",
  },
  {
    pmid: "27340741",
    title: "Basosquamous Carcinoma: Controversy, Advances, and Future Directions",
    authors: "Tan CZ, Rieger KE, Sarin KY",
    journal: "Dermatologic surgery : official publication for American Society for Dermatologic Surgery [et al.]",
    year: 2017,
    date: "January 2017",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27340741/",
    doiUrl: "https://doi.org/10.1097/DSS.0000000000000815",
  },
  {
    pmid: "26729755",
    title: "A survey of direct-to-consumer teledermatology services available to US patients: Explosive growth, opportunities and controversy",
    authors: "Fogel AL, Sarin KY",
    journal: "Journal of telemedicine and telecare",
    year: 2017,
    date: "January 2017",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/26729755/",
    doiUrl: "https://doi.org/10.1177/1357633X15624044",
  },
  {
    pmid: "28030567",
    title: "Tumor-Derived Suppressor of Fused Mutations Reveal Hedgehog Pathway Interactions",
    authors: "Urman NM, Mirza A, Atwood SX, Whitson RJ, et al.",
    journal: "PloS one",
    year: 2016,
    date: "2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28030567/",
    doiUrl: "https://doi.org/10.1371/journal.pone.0168031",
  },
  {
    pmid: "27614530",
    title: "Direct-to-consumer teledermatology services for pediatric patients: Room for improvement",
    authors: "Fogel AL, Teng J, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2016,
    date: "November 2016",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27614530/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2016.08.002",
  },
  {
    pmid: "27367170",
    title: "Assessment of Accuracy of Patient-Initiated Differential Diagnosis Generation by Google Reverse Image Searching",
    authors: "Ransohoff JD, Li S, Sarin KY",
    journal: "JAMA dermatology",
    year: 2016,
    date: "October 2016",
    researchArea: "Other",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27367170/",
    doiUrl: "https://doi.org/10.1001/jamadermatol.2016.2096",
  },
  {
    pmid: "27539887",
    title: "Genome-wide association study identifies 14 novel risk alleles associated with basal cell carcinoma",
    authors: "Chahal HS, Wu W, Ransohoff KJ, Yang L, et al.",
    journal: "Nature communications",
    year: 2016,
    date: "August 2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27539887/",
    doiUrl: "https://doi.org/10.1038/ncomms12510",
  },
  {
    pmid: "27424798",
    title: "Genome-wide association study identifies novel susceptibility loci for cutaneous squamous cell carcinoma",
    authors: "Chahal HS, Lin Y, Ransohoff KJ, Hinds DA, et al.",
    journal: "Nature communications",
    year: 2016,
    date: "July 2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27424798/",
    doiUrl: "https://doi.org/10.1038/ncomms12048",
  },
  {
    pmid: "26975725",
    title: "Identification of Alpha-Adrenergic Agonists as Potential Therapeutic Agents for Dermatomyositis through Drug-Repurposing Using Public Expression Datasets",
    authors: "Cho HG, Fiorentino D, Lewis M, Sirota M, et al.",
    journal: "The Journal of investigative dermatology",
    year: 2016,
    date: "July 2016",
    researchArea: "Autoimmune and Systemic Disease",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/26975725/",
    doiUrl: "https://doi.org/10.1016/j.jid.2016.03.001",
  },
  {
    pmid: "26546616",
    title: "An Investigator-Initiated Open-Label Trial of Sonidegib in Advanced Basal Cell Carcinoma Patients Resistant to Vismodegib",
    authors: "Danial C, Sarin KY, Oro AE, Chang AL",
    journal: "Clinical cancer research : an official journal of the American Association for Cancer Research",
    year: 2016,
    date: "March 2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/26546616/",
    doiUrl: "https://doi.org/10.1158/1078-0432.CCR-15-1588",
  },
  {
    pmid: "26892653",
    title: "Familial skin cancer syndromes: Increased risk of nonmelanotic skin cancers and extracutaneous tumors",
    authors: "Jaju PD, Ransohoff KJ, Tang JY, Sarin KY",
    journal: "Journal of the American Academy of Dermatology",
    year: 2016,
    date: "March 2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/26892653/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2015.08.073",
  },
  {
    pmid: "26892652",
    title: "Familial skin cancer syndromes: Increased melanoma risk",
    authors: "Ransohoff KJ, Jaju PD, Tang JY, Carbone M, et al.",
    journal: "Journal of the American Academy of Dermatology",
    year: 2016,
    date: "March 2016",
    researchArea: "Skin Cancer",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/26892652/",
    doiUrl: "https://doi.org/10.1016/j.jaad.2015.09.070",
  },
];
